dist: xenial
install:
- for i in $(cat .circle-ruby) ; do rvm install $i || exit 1 ; done
- for i in $(cat .circle-ruby) ; do rvm-exec $i bundle install || exit 1 ; done
script:
- for i in $(cat .circle-ruby) ; do rvm-exec $i bundle exec rake || exit 1 ; done
notifications:
  email: false
  slack:
    secure: ehWb/wXaDTuHtbZfT3KjxezGhR5lFQ3Wlpoks0WI11gpfsdnhKjVc09mqm6DAlN50LkWqIPBgWBM5uvuBBnmTu9XDAaDdC7rGUrv+IgXqrxC90UkIqq+qNVkvHLPy2mvGr3mskm86mkFingJ3t9zuZnvog/mNGxVKYpXwLibYAIEyd63IuUn0KfH/oOGTKv5GdKw1wYpdeBOt6dPnSKdosAanRW6nlmbJAVlaxcE3SQiZO9a2VpLrOQNEKZFBd0fPF8twJshArW9+S9e+EfA6aPnVo+jNl7TRsXitddL3g3RefLF/KsAbUaLxYgbsuMHKtpyc7FwJsTsMf923Ohc6Jb6oP42cIKjco95IZ4fXlvvK/K6/F81Xww8rnbd+gDQ3e92EM5axLBCf9J/7fKA5Ka1V1GdUykMkT4oSyGxtgiMnA1loqyrFrVPdwNPOGn/lnsYTrK5qGsA+u4l1vdrAQTphl+BGsdRqAM1CRLSn6M8oFQt59157Qn2ZvmXFdoq29lAcgTyY8Y1TV5LJXhG3KbUqHu6fr9kp8d+sS5HqXo8AQlvYQ3PMfibg98QCK/2F4/M0Efbd4cIkQL46XOY9FkPD6OIw3OQNZcscNhM1ZSMIV86uvdamgofggvuWoYsasYyEJ/htmsomlGJReUvzBcASSMCl8a+6QxBjF3uT94=
